# Generated by Django 4.2.4 on 2023-09-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='url',
            field=models.URLField(default=0.005997001499250375, max_length=100),
            preserve_default=False,
        ),
    ]
